export const enum ThunesTransactionStatus {
  REQUEST = 'REQUEST',

  QUOTATION = 'QUOTATION',

  CREATED = 'CREATED',

  CONFIRMED = 'CONFIRMED',

  CONFIRMED_UNDER_REVIEW_SLS = 'CONFIRMED_UNDER_REVIEW_SLS',

  CONFIRMED_WAITING_FOR_PICKUP = 'CONFIRMED_WAITING_FOR_PICKUP',

  REJECTED = 'REJECTED',

  REJECTED_SLS_SENDER = 'REJECTED_SLS_SENDER',

  REJECTED_SLS_BENEFICIARY = 'REJECTED_SLS_BENEFICIARY',

  REJECTED_INVALID_BENEFICIARY = 'REJECTED_INVALID_BENEFICIARY',

  REJECTED_BARRED_BENEFICIARY = 'REJECTED_BARRED_BENEFICIARY',

  REJECTED_INVALID_BENEFICIARY_DETAILS = 'REJECTED_INVALID_BENEFICIARY_DETAILS',

  REJECTED_LIMITATIONS_ON_TRANSACTION_VALUE = 'REJECTED_LIMITATIONS_ON_TRANSACTION_VALUE',

  REJECTED_LIMITATIONS_ON_SENDER_VALUE = 'REJECTED_LIMITATIONS_ON_SENDER_VALUE',

  REJECTED_LIMITATIONS_ON_BENEFICIARY_VALUE = 'REJECTED_LIMITATIONS_ON_BENEFICIARY_VALUE',

  REJECTED_LIMITATIONS_ON_ACCOUNT_VALUE = 'REJECTED_LIMITATIONS_ON_ACCOUNT_VALUE',

  REJECTED_LIMITATIONS_ON_SENDER_QUANTITY = 'REJECTED_LIMITATIONS_ON_SENDER_QUANTITY',

  REJECTED_LIMITATIONS_ON_BENEFICIARY_QUANTITY = 'REJECTED_LIMITATIONS_ON_BENEFICIARY_QUANTITY',

  REJECTED_LIMITATIONS_ON_ACCOUNT_QUANTITY = 'REJECTED_LIMITATIONS_ON_ACCOUNT_QUANTITY',

  REJECTED_PAYER_CURRENTLY_UNAVAILABLE = 'REJECTED_PAYER_CURRENTLY_UNAVAILABLE',

  REJECTED_INSUFFICIENT_BALANCE = 'REJECTED_INSUFFICIENT_BALANCE',

  CANCELLED = 'CANCELLED',

  SUBMITTED = 'SUBMITTED',

  AVAILABLE = 'AVAILABLE',

  COMPLETED = 'COMPLETED',

  REVERSED = 'REVERSED',

  DECLINED = 'DECLINED',

  DECLINED_SLS_SENDER = 'DECLINED_SLS_SENDER',

  DECLINED_SLS_BENEFICIARY = 'DECLINED_SLS_BENEFICIARY',

  DECLINED_INVALID_BENEFICIARY = 'DECLINED_INVALID_BENEFICIARY',

  DECLINED_BARRED_BENEFICIARY = 'DECLINED_BARRED_BENEFICIARY',

  DECLINED_UNSUPPORTED_BENEFICIARY = 'DECLINED_UNSUPPORTED_BENEFICIARY',

  DECLINED_INVALID_BENEFICIARY_DETAILS = 'DECLINED_INVALID_BENEFICIARY_DETAILS',

  DECLINED_LIMITATIONS_ON_TRANSACTION_VALUE = 'DECLINED_LIMITATIONS_ON_TRANSACTION_VALUE',

  DECLINED_LIMITATIONS_ON_SENDER_VALUE = 'DECLINED_LIMITATIONS_ON_SENDER_VALUE',

  DECLINED_LIMITATIONS_ON_BENEFICIARY_VALUE = 'DECLINED_LIMITATIONS_ON_BENEFICIARY_VALUE',

  DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE = 'DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE',

  DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_DAILY = 'DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_DAILY',

  DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_WEEKLY = 'DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_WEEKLY',

  DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_MONTHLY = 'DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_MONTHLY',

  DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_YEARLY = 'DECLINED_LIMITATIONS_ON_ACCOUNT_VALUE_YEARLY',

  DECLINED_LIMITATIONS_ON_SENDER_QUANTITY = 'DECLINED_LIMITATIONS_ON_SENDER_QUANTITY',

  DECLINED_LIMITATIONS_ON_BENEFICIARY_QUANTITY = 'DECLINED_LIMITATIONS_ON_BENEFICIARY_QUANTITY',

  DECLINED_LIMITATIONS_ON_ACCOUNT_QUANTITY = 'DECLINED_LIMITATIONS_ON_ACCOUNT_QUANTITY',

  DECLINED_PAYER_CURRENTLY_UNAVAILABLE = 'DECLINED_PAYER_CURRENTLY_UNAVAILABLE',
}
